services:
  redis:
   image: redis:7-alpine
   container_name: redis-container
   volumes:
     - redis_data:/data


  server:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - SECRETE_KEY=${SECRETE_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}

    depends_on:
    - redis

  worker:
    build:
      # context: contextPath
      # dockerfile: Dockerfile
      context: .
    container_name: email-worker
    command: ["node", "src/worker.js"]
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
    - redis

volumes:
    redis_data:

  