const UserRole = {
  TENANT_BUYER: 'TENANT_BUYER',
  LANDLORD_OWNER: 'LANDLORD_OWNER',
  AGENT_BROKER: 'AGENT_BROKER',
  ADMIN_MODERATOR: 'ADMIN_MODERATOR',
  FIELD_INSPECTOR: 'FIELD_INSPECTOR',
};

const VerificationStatus = {
  UNVERIFIED: 'UNVERIFIED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  FIELD_VERIFIED: 'FIELD_VERIFIED',
  GOV_MALPOT_VERIFIED: 'GOV_MALPOT_VERIFIED',
  REJECTED: 'REJECTED',
};

const TransactionIntent = {
  FOR_SALE: 'FOR_SALE',
  FOR_RENT: 'FOR_RENT',
  LEASE: 'LEASE',
};

const PropertyCategory = {
  ROOM: 'ROOM',
  FLAT_APARTMENT: 'FLAT_APARTMENT',
  INDEPENDENT_HOUSE: 'INDEPENDENT_HOUSE',
  LAND_PLOT: 'LAND_PLOT',
  OFFICE_SPACE: 'OFFICE_SPACE',
  SHOP_COMMERCIAL: 'SHOP_COMMERCIAL',
  BUILDING_COMPLEX: 'BUILDING_COMPLEX',
  WAREHOUSE: 'WAREHOUSE',
};

const LandSystemStandard = {
  VALLEY_ROPANI: 'VALLEY_ROPANI', // 1 Ropani = 16 Aana = 64 Paisa = 256 Daam
  TERAI_BIGHA: 'TERAI_BIGHA',     // 1 Bigha = 20 Kattha = 400 Dhur
  METRIC_SQFT: 'METRIC_SQFT',     // Fallback
};

const RoadSurfaceType = {
  BLACKTOPPED_PITCHED: 'BLACKTOPPED_PITCHED',
  GRAVEL: 'GRAVEL',
  DHALAN_CONCRETE: 'DHALAN_CONCRETE',
  SOIL_DIRT: 'SOIL_DIRT',
  PLANNED: 'PLANNED',
};

const VastuFacing = {
  EAST: 'EAST',
  NORTH: 'NORTH',
  NORTH_EAST: 'NORTH_EAST',
  WEST: 'WEST',
  NORTH_WEST: 'NORTH_WEST',
  SOUTH: 'SOUTH',
  SOUTH_EAST: 'SOUTH_EAST',
  SOUTH_WEST: 'SOUTH_WEST',
};

const AppointmentStatus = {
  REQUESTED: 'REQUESTED',
  CONFIRMED_OWNER: 'CONFIRMED_OWNER',
  COORDINATOR_ASSIGNED: 'COORDINATOR_ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  COMPLETED: 'COMPLETED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED',
};

const WalkthroughType = {
  SELF_WALKTHROUGH: 'SELF_WALKTHROUGH',
  ACCOMPANIED_EXPERT: 'ACCOMPANIED_EXPERT',
};

const EscrowProvider = {
  ESEWA: 'ESEWA',
  KHALTI: 'KHALTI',
  CONNECT_IPS: 'CONNECT_IPS',
  FONEPAY: 'FONEPAY',
};

const LeaseStatus = {
  DRAFT: 'DRAFT',
  PENDING_SIGNATURES: 'PENDING_SIGNATURES',
  ACTIVE_TENANCY: 'ACTIVE_TENANCY',
  EXPIRED: 'EXPIRED',
  TERMINATED: 'TERMINATED',
};

module.exports = {
  UserRole,
  VerificationStatus,
  TransactionIntent,
  PropertyCategory,
  LandSystemStandard,
  RoadSurfaceType,
  VastuFacing,
  AppointmentStatus,
  WalkthroughType,
  EscrowProvider,
  LeaseStatus,
};